name: Playwright Tests -Docker
on:
  push:
    branches: [ main ]
jobs:
  test-docker-playwright:
    runs-on: ubuntu-latest
    # Using the official Playwright Docker container as the 'container' for the job
    container:
      image: mcr.microsoft.com/playwright:v1.59.1-noble
      options: --user 1001 --ipc=host

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run Playwright tests
        run: npx playwright test
        continue-on-error: true # Ensure the report generates even if tests fail

      - name: Set up Java for Allure
        if: always()
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: Generate Allure Report
        if: always()
        run: npx allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Deploy Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'